api:
  host: "0.0.0.0"
  port: 8080

model:
  checkpoint: "chunkformer-large-vie"
  chunk_size: 64
  left_context_size: 128
  right_context_size: 128
  total_batch_duration: 1800

cache:
  dir: "./cache"
  max_age_hours: 24

audio:
  frame_rate: 16000
  sample_width: 2
  channels: 1

features:
  num_mel_bins: 80
  frame_length: 25
  frame_shift: 10
  dither: 0.0
  energy_floor: 0.0
  sample_frequency: 16000

logging:
  version: 1
  disable_existing_loggers: true

  formatters:
    simple:
      format: "{asctime} | {levelname: <8} | {name}:{funcName}:{lineno} - {message}"
      style: "{"

  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      level: DEBUG
      stream: ext://sys.stdout

    file:
      class: logging.handlers.RotatingFileHandler
      formatter: simple
      level: INFO
      filename: logs/app.log
      maxBytes: 10485760 # 10MB
      backupCount: 10
      encoding: utf8

  loggers:
    "": # root logger
      handlers: [console, file]
      level: INFO
      propagate: no

  development:
    loggers:
      "":
        handlers: [console]
        level: DEBUG

  production:
    loggers:
      "":
        handlers: [file]
        level: WARNING
